config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'reminders#index'
  resources :reminders
  resources :notifications, only: [:index]
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/remaind_item.rb
class RemaindItem < ApplicationRecord
    belongs_to :user
    has_many :remainds

    validates :description, length: { maximum: 140 }
end

app/models/remind.rb
class Remind < ApplicationRecord
  belongs_to :remind_item
end

app/models/remind_item.rb
class RemindItem < ApplicationRecord
    belongs_to :user
    has_many :reminds, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :remind_items, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  attr_accessor :remember_token

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user

  def index
    reminds = Remind.joins(:remind_item)
                    .where(notified: false)
                    .where("remind_at <= ?", Time.now)
                    .where(remind_item: {user: current_user})
    reminds.update(notified: true)
    render json: reminds, include: [:remind_item]
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :logged_in_user

  def index
    @reminders = RemindItem.where(user: current_user)
  end

  def show
    @reminder = RemindItem.find(params[:id])
    @remind = @reminder.reminds.first
  end


  def new
    @remind_item = RemindItem.new
    @remind = Remind.new
  end

  def edit
  end

  def create
    remind_item = RemindItem.new(remind_item_params)
    remind_item.user = current_user
    remind_item.reminds.build(remind_params)
    respond_to do |format|
      if remind_item.save
        format.html { redirect_to reminders_url, notice: "reminders was successfully created." }
       # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
       # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    remind = Remind.find(params[:id])
    respond_to do |format|
      if remind.update(remind_params)
        format.html { redirect_to reminders_url, notice: "reminders was successfully edited." }
      else
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    remind_item = RemindItem.find(params[:id])
    remind_item.destroy

    respond_to do |format|
      format.html { redirect_to reminders_url, notice: "Task was successfully destroyed." }

    end
  end

  private
    def remind_item_params
        params.require(:remind_item).permit(:description)
    end
    
    def remind_params
      params.require(:remind).permit(:remind_at)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Reminder!"
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light p-3" style="background-color: #FEBA0A;">
    <div class="collapse navbar-collapse" id="navbarNav">
      <a class="navbar-brand" href="/">Reminder</a>
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Reminders", reminders_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Log out", logout_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reminder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/reminders/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="reminder-header">
  <div class="align-right new-button">
    <%= button_to '登録', {controller: 'reminders', action: 'new'}, {method: :get} %>
  </div>
</div>
<div id="reminders" class="reminders">
  <ul class="list-group list-group-flush">
    <% @reminders.each do |reminder| %>
      <li id="<%= dom_id reminder %>" class="list-group-item">
        <div id="container">
          <%= link_to reminder_path(reminder.id) do %>
            <div class="inline"><%= reminder.description %></div>
          <% end %>
            <div class="inline align-right"><%= reminder.reminds[0].remind_at.strftime('%Y年%m月%d日 %H:%M') %></div>
          <%= link_to image_tag('trash.svg', class: 'trash'), reminder_path(reminder.id), data: { turbo_method: :delete } %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/reminders/new.html.erb
<div id="new-task-body">
  <%= form_with(model: @remind_item, url: reminders_path) do |form| %>

    <div id="new-task-content">
    <%= form.label "内容", style: "display: block" %>
    <%= form.text_field :description %>

    <%= fields_for :remind, @remind_item.reminds.first do |remind_form| %>
      <%= form.label "日時", style: "display: block" %>
      <%= remind_form.datetime_field :remind_at %>
    <% end %>
    </div>
    <%= form.submit "登録" %>
  <% end %>
  <%= link_to "戻る", reminders_path %>
</div>

app/views/reminders/show.html.erb
<h1>This task</h1>

<p style="color: green"><%= notice %></p>

<%#= render @reminder %>
<div id="<%= dom_id @reminder %>">
  <p>
  <strong>description:</strong>
    <%= @reminder.description %>
  <strong>remind date:</strong>
    <%= @reminder.reminds[0].remind_at %>
  </p>

  <% if @reminder.reminds[0].notified == true %>
    <%= form_with(model: @remind, url: reminder_path(@reminder.id), method: "put")  do |formUpdate| %>
      <!--フォーム内容 -->
      <%= formUpdate.datetime_field :remind_at %>
      <%= formUpdate.submit "再通知設定" %>
    <% end %>
  <% end %>
</div>
<div>

  <%= link_to "Back to tasks", reminders_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: 'form-control'%>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :password_confirmation, "Confirmation", style: "display: block" %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="reminders" class="reminders">
  <ul class="list-group list-group-flush">
    <% @users.each do |user| %>
      <li id="<%= dom_id user %>" class="list-group-item">
        <div id="container">
          <%= link_to user_path(user.id) do %>
            <div class="inline"><%= user.name %></div>
            <div class="inline">(<%= user.email %>)</div>
          <% end %>
          <%= link_to image_tag('trash.svg', class: 'trash'), user_path(user.id), data: { turbo_method: :delete } %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New user", new_user_path, {class: "btn btn-primary mx-1"} %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
</div>